source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'App' do
  pod 'NSURL+QueryDictionary'
  pod 'Szimpla/Server', :path => '../'
end

target "AppUITests" do
  pod 'Szimpla/Client', :path => '../'
end