# Requires
require 'yaml'

# Fastlane Constants
fastlane_version "1.54.0"
default_platform :ios

# Constants
PODSPEC = "Szimpla.podspec"
WORKSPACE = "Example/Szimpla.xcworkspace"
SCHEME_TESTS = "Szimpla-Example"
REPOSITORY = "pepibumur/Szimpla"
PODFILE = "Example/Podfile"

# Lanes
desc "Setup everything needed to work on the project"
lane :setup do
  cocoapods(podfile: PODFILE)
end

desc "Runs the tests suite"
lane :tests do
  scan(workspace: WORKSPACE, scheme: SCHEME_TESTS, skip_build: true)
end

desc "Runs everything needed for CI"
lane :ci do
  setup
  tests
end
